import os
import tempfile
import sys
from pathlib import Path
from typing import Any
import re

import pandas as pd
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from declareppipilot import run_full_pipeline
from declareppipilot.models import LLMConfig


app = FastAPI(title="PPIDeclarePilot Dashboard API")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
FRONTEND_DIST_DIR = PROJECT_ROOT / "webapp" / "frontend" / "dist"
LEGACY_STATIC_DIR = PROJECT_ROOT / "webapp" / "static"

if (FRONTEND_DIST_DIR / "assets").exists():
    app.mount("/assets", StaticFiles(directory=str(FRONTEND_DIST_DIR / "assets")), name="assets")
if LEGACY_STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(LEGACY_STATIC_DIR)), name="legacy-static")


class HealthResponse(BaseModel):
    status: str


def _parse_optional_float(raw: str | None) -> float | None:
    if raw is None or raw.strip() == "":
        return None
    return float(raw)


def _build_time_freq(quantity: int | None, unit: str | None) -> str:
    if quantity is None or quantity <= 0:
        raise ValueError("Time quantity must be a positive integer.")
    unit_map = {
        "week": "WE",
        "month": "ME",
        "year": "YE",
    }
    if unit not in unit_map:
        raise ValueError("Invalid time unit. Use week, month, or year.")
    return f"{quantity}{unit_map[unit]}"


def _build_llm_config(
    provider: str,
    model: str,
    base_url: str | None,
    api_key: str | None,
    temperature: str | None,
    max_output_tokens: str | None,
    json_retries: str | None,
) -> LLMConfig:
    provider = provider.strip().lower()
    if provider not in {"openai", "anthropic", "lmstudio"}:
        raise ValueError("provider must be one of: openai, anthropic, lmstudio")

    api_key_env = None
    if api_key and api_key.strip():
        env_name = f"WEBAPP_{provider.upper()}_API_KEY"
        os.environ[env_name] = api_key.strip()
        api_key_env = env_name

    temp = _parse_optional_float(temperature)
    max_tokens = int(max_output_tokens) if max_output_tokens and max_output_tokens.strip() else None
    retries = int(json_retries) if json_retries and json_retries.strip() else 2

    return LLMConfig(
        provider=provider,
        model=model.strip(),
        base_url=base_url.strip() if base_url and base_url.strip() else None,
        api_key_env=api_key_env,
        temperature=temp,
        max_output_tokens=max_tokens,
        json_retries=retries,
    )


def _normalize_result(
    *,
    run_result,
    final_report,
    time_grouper_freq: str | None,
    min_support: float,
    cv_threshold: float | None,
) -> dict[str, Any]:
    kpi_by_id = {k.id: k for k in run_result.kpi_set.kpis}
    exe_by_id = {e.kpi_id: e for e in run_result.executions}
    cat_by_id = {c.kpi_id: c for c in run_result.kpi_categories.kpi_categories}
    readable_by_id = {}
    if run_result.readable_ppi_definitions is not None:
        readable_by_id = {item.kpi_id: item for item in run_result.readable_ppi_definitions.items}
    var_by_id = {}
    if run_result.variability_results is not None:
        var_by_id = {v.kpi_id: v for v in run_result.variability_results}

    grouped: dict[str, dict[str, Any]] = {}
    for kpi_id, kpi in kpi_by_id.items():
        category = cat_by_id.get(kpi_id)
        goal_name = category.goal_name if category is not None else "Uncategorized"
        if goal_name not in grouped:
            grouped[goal_name] = {
                "goal_name": goal_name,
                "goal_description": None if category is None else category.goal_description,
                "kpis": [],
            }

        execution = exe_by_id.get(kpi_id)
        readable = readable_by_id.get(kpi_id)
        variability = var_by_id.get(kpi_id)

        grouped[goal_name]["kpis"].append(
            {
                "kpi_id": kpi_id,
                "objective": kpi.objective,
                "category_rationale": None if category is None else category.rationale,
                "kpi_metric_str": None if execution is None else execution.kpi_metric_str,
                "human_readable_definition": None if readable is None else readable.human_readable_definition,
                "human_readable_rationale": None if readable is None else readable.rationale,
                "human_readable_warning": "This text was generated by AI.",
                "single_value": None if execution is None else execution.kpi_metric_computation_value,
                "grouped_values": None if variability is None else _normalize_grouped_values_for_api(variability.grouped_values),
                "coefficient_of_variation": None if variability is None else variability.coefficient_of_variation,
                "cv_flag_below_threshold": None if variability is None else variability.cv_flag_below_threshold,
                "variability_status": None if variability is None else variability.status,
                "execution_status": None if execution is None else execution.final_status,
                "execution_error": None if execution is None else execution.last_error,
            }
        )

    goals = sorted(grouped.values(), key=lambda x: x["goal_name"].lower())
    final_report_records = final_report.astype(object).where(pd.notna(final_report), None).to_dict(orient="records")
    return {
        "meta": {
            "time_grouper_freq": time_grouper_freq,
            "min_support": min_support,
            "cv_threshold": cv_threshold,
            "n_kpis": len(kpi_by_id),
            "n_goals": len(goals),
        },
        "goals": goals,
        "final_report": final_report_records,
    }


def _timedelta_to_iso8601(value: pd.Timedelta) -> str:
    total_seconds = int(value.total_seconds())
    sign = "-" if total_seconds < 0 else ""
    total_seconds = abs(total_seconds)
    days, remainder = divmod(total_seconds, 86400)
    hours, remainder = divmod(remainder, 3600)
    minutes, seconds = divmod(remainder, 60)
    microseconds = abs(int(value.microseconds))
    if microseconds > 0:
        second_text = f"{seconds}.{microseconds:06d}".rstrip("0").rstrip(".")
    else:
        second_text = str(seconds)
    return f"{sign}P{days}DT{hours}H{minutes}M{second_text}S"


def _normalize_group_value_for_api(value: Any) -> tuple[Any, float | None]:
    if value is None:
        return None, None
    if isinstance(value, (int, float)) and pd.notna(value):
        return float(value), float(value)
    if isinstance(value, pd.Timedelta):
        return _timedelta_to_iso8601(value), float(value.total_seconds())

    text = str(value).strip()
    if text == "":
        return "", None

    numeric_match = re.fullmatch(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", text)
    if numeric_match:
        num = float(text)
        return num, num

    td = pd.to_timedelta(text, errors="coerce")
    if pd.notna(td):
        return _timedelta_to_iso8601(td), float(td.total_seconds())

    return text, None


def _normalize_grouped_values_for_api(grouped_values: list[dict[str, Any]] | None) -> list[dict[str, Any]] | None:
    if grouped_values is None:
        return None
    normalized: list[dict[str, Any]] = []
    for item in grouped_values:
        if not isinstance(item, dict):
            continue
        bucket = item.get("bucket")
        value = item.get("value")
        norm_value, norm_numeric = _normalize_group_value_for_api(value)
        normalized.append(
            {
                "bucket": None if bucket is None else str(bucket),
                "value": norm_value,
                "value_numeric": norm_numeric,
            }
        )
    return normalized


@app.get("/health", response_model=HealthResponse)
def health() -> HealthResponse:
    return HealthResponse(status="ok")


@app.get("/")
def index() -> FileResponse:
    if (FRONTEND_DIST_DIR / "index.html").exists():
        return FileResponse(str(FRONTEND_DIST_DIR / "index.html"))
    return FileResponse(str(LEGACY_STATIC_DIR / "index.html"))


@app.post("/api/run")
async def run_pipeline(
    event_log_file: UploadFile = File(...),
    provider: str = Form(...),
    model: str = Form(...),
    base_url: str | None = Form(None),
    api_key: str | None = Form(None),
    temperature: str | None = Form(None),
    max_output_tokens: str | None = Form(None),
    json_retries: str | None = Form("2"),
    use_attributes: bool = Form(False),
    min_support: str | None = Form(None),
    period_enabled: bool = Form(False),
    period_quantity: int | None = Form(1),
    period_unit: str | None = Form("month"),
    cv_threshold: str | None = Form(None),
):
    if not event_log_file.filename.lower().endswith(".xes"):
        raise HTTPException(status_code=400, detail="Please upload a .xes file.")

    min_support_value = float(min_support) if min_support and min_support.strip() else 0.8
    cv_threshold_value = _parse_optional_float(cv_threshold)

    try:
        # Period grouping is mandatory for dashboard execution. Default is 1 month.
        _ = period_enabled  # kept for backward form compatibility
        time_grouper_freq = _build_time_freq(
            period_quantity if period_quantity is not None else 1,
            period_unit if period_unit is not None else "month",
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    if cv_threshold_value is None:
        cv_threshold_value = 0.2

    try:
        llm_config = _build_llm_config(
            provider=provider,
            model=model,
            base_url=base_url,
            api_key=api_key,
            temperature=temperature,
            max_output_tokens=max_output_tokens,
            json_retries=json_retries,
        )
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Invalid LLM configuration: {exc}") from exc

    try:
        with tempfile.NamedTemporaryFile(suffix=".xes", delete=False) as tmp:
            content = await event_log_file.read()
            tmp.write(content)
            tmp_path = tmp.name

        from Declare4Py.D4PyEventLog import D4PyEventLog

        event_log = D4PyEventLog(case_name="case:concept:name")
        event_log.parse_xes_log(tmp_path)

        run_result, final_report = run_full_pipeline(
            event_log=event_log,
            llm_config=llm_config,
            min_support=min_support_value,
            use_attributes=use_attributes,
            time_grouper_freq=time_grouper_freq,
            cv_threshold=cv_threshold_value,
        )

        return _normalize_result(
            run_result=run_result,
            final_report=final_report,
            time_grouper_freq=time_grouper_freq,
            min_support=min_support_value,
            cv_threshold=cv_threshold_value,
        )
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Pipeline execution failed: {exc}") from exc
    finally:
        try:
            if 'tmp_path' in locals() and os.path.exists(tmp_path):
                os.remove(tmp_path)
        except Exception:
            pass
